language: python
python:
  - 3.9

install:
    - sudo apt-get update -y
    - bash .travis_install.sh
    - pip install coverage objgraph
    - pip freeze

script:
    - nosetests --with-coverage --cover-package=minpower
