language: python
python:
  - 3.9

install:
    - bash .travis_install.sh
    - pip install coverage objgraph

script:
    - nosetests --with-coverage --cover-package=minpower

branches:
  only:
    - master
