language: python
python:
  - 3.9

addons:
  apt:
    update: true

install:
    - sudo apt-get install -y glpk-utils
    - pip install .
    - pip install coverage objgraph
    - pip freeze

script:
    - nosetests --with-coverage --cover-package=minpower
