language: python
python:
  - 3.9

addons:
  apt:
    update: true

install:
    - bash .travis_install.sh
    - pip install coverage objgraph
    - pip freeze

script:
    - nosetests --with-coverage --cover-package=minpower
